/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Program */

#ifndef _Included_Program
#define _Included_Program
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Program
 * Method:    gcd
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_Program_gcd
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     Program
 * Method:    reverseOf
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Program_reverseOf
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Program
 * Method:    squareAll
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_Program_squareAll
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
